### ISSUE TITLE
Watching stream of multi-words games?

### ISSUE THREAD

**Issue by Kraker01** [AlexSterk/TwitchDropGrabber#26]
Script is running fine with 1-word games (fortnite, smite, valorant...) but I'm experiencing problems in games like "Black Desert Online". If i don't leave any space between words, this is what happens:
C:\TwitchDropGrabber-latest>npm start -- BlackDesertOnline

> twitch-drop-grabber@2021.06.13.1 start
> node dist/index.js "BlackDesertOnline"

[Wed, 18 Aug 2021 13:55:46 GMT] Starting application
[Wed, 18 Aug 2021 13:55:47 GMT] Navigating to Twitch
[Wed, 18 Aug 2021 13:55:54 GMT] Configuring streaming settings
[Wed, 18 Aug 2021 13:55:54 GMT] Signing in using auth-token
[Wed, 18 Aug 2021 13:55:54 GMT] Finding online channel...

If i write with correct spaces, this i what happens:
C:\TwitchDropGrabber-latest>npm start -- Black Desert Online

> twitch-drop-grabber@2021.06.13.1 start
> node dist/index.js "Black" "Desert" "Online"

C:\TwitchDropGrabber-latest\node_modules\command-line-args\dist\index.js:1345
        throw err
        ^

UNKNOWN_VALUE: Unknown value: Desert
    at commandLineArgs (C:\TwitchDropGrabber-latest\node_modules\command-line-args\dist\index.js:1342:21)
    at Object.<anonymous> (C:\TwitchDropGrabber-latest\dist\index.js:46:12)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  value: 'Desert'
}

**Comment by AlexSterk** [comment]
Just copy how Twitch does it in its own URL
![image](https://user-images.githubusercontent.com/13663706/129940917-bdc2d566-3820-40ae-a8a4-ab5c176a3286.png)

**Comment by Kraker01** [comment]
It worked, but the script keep fetching channel list and never start watching.

**Comment by AlexSterk** [comment]
Try putting it in quotes: `npm start -- "Black%20Desert%20Online"`
